### ISSUE TITLE
suggest ejs file support Emment feature

### ISSUE THREAD

**Issue by vimcaw** [gregory-m/ejs-tmbundle#4]
VS Code support Emment in html file, can you transplant this feature to ejs file?

**Comment by flyweights** [comment]
If you have a quick set of output

**Comment by vimcaw** [comment]
I have sloved it by adding following configuration:
```json
"emmet.includeLanguages": {
    "ejs": "html"
}
```
https://code.visualstudio.com/docs/editor/emmet#_emmet-configuration
